---

os: osx
osx_image: xcode12.2
language: objective-c

install:
  - sudo pip3 install pip --upgrade
  - sudo pip3 install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../' | tee ansible.cfg
  - brew install mas

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
