---
os: osx
osx_image: xcode8.2
language: objective-c

install:
  - sudo easy_install pip
  - sudo pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../' | tee ansible.cfg

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
